---
kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: golang:1.14.0-alpine
  commands:
  - env BUILDTAGS="exclude_graphdriver_btrfs exclude_graphdriver_devicemapper" CGO_ENABLED=0 go build
